services:
  db:
    container_name: postgres
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
